### ISSUE TITLE
Nothing is saved in bin

### ISSUE THREAD

**Issue by arunmagesh** [andre-richter/arduino-spi-read-eeprom#2]
Hello,
I have connected my 25lc080 to my arduino and i ran the C program and i am not getting any eeprom data saved to the bin file. 
In arduino serial console. if i press random letters i get some dump data. 
![screenshot from 2016-08-10 11-58-51](https://cloud.githubusercontent.com/assets/8372164/17543987/0924c4ac-5ef2-11e6-888e-d4a845822404.png)
![screenshot from 2016-08-10 12-01-06](https://cloud.githubusercontent.com/assets/8372164/17544008/2fca6b66-5ef2-11e6-8db0-e505ed230875.png)

**Comment by andre-richter** [comment]
I had a quick glance at the datasheet of your EEPROM. It seems to use 16 bit addresses, while my code is written for 24 bit addresses.

Please test again after deleting this line:
https://github.com/andre-richter/arduino-spi-read-eeprom/blob/master/spi_read_eeprom.ino#L27

**Comment by arunmagesh** [comment]
Thanks. It worked. :) Even without removing it. 
Problem was with the serial port. I ran the program and tried sending some data using serial terminal to initialize the data dump!
